[package]
name = "burrito-ss"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
orion = { version = "^0.17" }
secrets = "^1.2"
anyhow = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
bson = "^2.11"